version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "python-app"  # Must match your container name exactly
          ContainerPort: 8080
InputArtifacts:
  - Name: "build_output"
    Source:
      - "taskdef.json"
      - "appspec.yml"
# Hooks:
#   - BeforeInstall: "ValidateService"
#   - AfterInstall: "AfterInstall"
#   - AfterAllowTestTraffic: "AfterAllowTestTraffic"
#   - BeforeAllowTraffic: "BeforeAllowTraffic"
#   - AfterAllowTraffic: "AfterAllowTraffic"