version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "python-app"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-public-a", "subnet-public-b"]
            SecurityGroups: ["sg-ecs"]
            AssignPublicIp: "ENABLED"
# Hooks:
#   - BeforeInstall: "BeforeInstallHookFunctionArn"
#   - AfterInstall: "AfterInstallHookFunctionArn"
#   - AfterAllowTestTraffic: "AfterAllowTestTrafficHookFunctionArn"
#   - BeforeAllowTraffic: "BeforeAllowTrafficHookFunctionArn"
#   - AfterAllowTraffic: "AfterAllowTrafficHookFunctionArn"