version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Setting up task definition template...
      - cp taskdef.json.template taskdef.json
      - sed -i "s|EXECUTION_ROLE_ARN|$(aws ecs describe-task-definition --task-definition python-app --query taskDefinition.executionRoleArn --output text)|g" taskdef.json
      - sed -i "s|IMAGE1_NAME|$ECR_REPOSITORY_URI:$IMAGE_TAG|g" taskdef.json
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_URI:latest .
      - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      # Create directory if it doesn't exist
      - mkdir -p $CODEBUILD_SRC_DIR/output
      - echo "Generating image definitions..."
      - echo '[{"name":"python-app","imageUri":"'"$ECR_REPOSITORY_URI:$IMAGE_TAG"'"}]' > $CODEBUILD_SRC_DIR/output/imagedefinitions.json
       # Verify the file was created
      - echo "File contents:"
      - echo "--- imagedefinitions.json ---"
      - cat $CODEBUILD_SRC_DIR/output/imagedefinitions.json
      - echo "File size:"
      - ls -la $CODEBUILD_SRC_DIR/output/imagedefinitions.json
      - echo "Verifying artifacts..."
      - echo "--- appspec.yml ---"
      - cat appspec.yml
      - echo "--- taskdef.json ---"
      - cat taskdef.json
      - echo "File listing:"
      - ls -la

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - taskdef.json
  base-directory: $CODEBUILD_SRC_DIR  # Add this line
  discard-paths: no  # Changed to preserve directory structure
